version: "3.9"
services:
  app:
    build: .
    image: app
    ports:
      - "8192:8129"
    env_file:
      - .env
    environment:
      - PORT=8129
    volumes:
      - .:/code/app
      - gradio_cached_examples:/code/app/gradio_cached_examples
      - flagged:/code/app/flagged
    entrypoint: /bin/bash
volumes:
  gradio_cached_examples:
  flagged: