version: "3.9"
services:
  app:
    build: .
    image: app
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
      - gradio_cached_examples:/code/app/gradio_cached_examples
      - flagged:/code/app/flagged
    # entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    # entrypoint: tail -f /dev/null
volumes:
  gradio_cached_examples:
  flagged: