version: "3.9"
services:
  app:
    build:
      context: .
    image: app
    ports:
      - 8129:8129
    env_file:
      - .env
    environment:
      - PORT=8129
    volumes:
      - gradio_cached_examples:/code/app/gradio_cached_examples
      - flagged:/code/app/flagged
      - src:/code/app/src
    # entrypoint: uvicorn src.main:app --host 0.0.0.0 --port 8129 --reload --log-level debug
    entrypoint: /bin/bash
volumes:
  gradio_cached_examples:
  flagged: